# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-13 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facerecognation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_number', models.CharField(max_length=21, null=True)),
                ('Names', models.CharField(max_length=50, null=True)),
                ('Tel', models.CharField(max_length=21, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_number', models.CharField(max_length=21, null=True)),
                ('Names', models.CharField(max_length=50, null=True)),
                ('Destination', models.CharField(choices=[('StaffRoom', 'StaffRoom'), ('ComputerLab', 'ComputerLab'), ('EmployeeRoom', 'EmployeeRoom')], default='StaffRoom', max_length=50, null=True)),
                ('Tel', models.CharField(max_length=21, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idscan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_number', models.CharField(max_length=21, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipNumber', models.CharField(max_length=30, null=True)),
                ('owner', models.CharField(choices=[('visitor', 'visitor'), ('urrent_instutition', 'current_instutition'), ('visited_instutition', 'visited_instutition')], default='visitor', max_length=30, null=True)),
                ('Id_number', models.CharField(max_length=30, null=True)),
                ('Equip_Name', models.CharField(max_length=30, null=True)),
                ('Tel', models.CharField(max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rfidscan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFId_number', models.CharField(max_length=21, null=True)),
                ('Names', models.CharField(max_length=50, null=True)),
                ('Tel', models.CharField(max_length=21, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipNumber', models.CharField(max_length=100, null=True)),
                ('Names', models.CharField(max_length=100, null=True)),
                ('EquipName', models.CharField(choices=[('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('DestopMachine', 'DestopMachine')], default='Laptop', max_length=20, null=True)),
                ('Destination', models.CharField(max_length=30, null=True)),
                ('Owner', models.CharField(max_length=30, null=True)),
                ('Tel', models.CharField(max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Idnumber', models.CharField(max_length=30, null=True)),
                ('FirstName', models.CharField(max_length=30, null=True)),
                ('LastName', models.CharField(max_length=30, null=True)),
                ('EntryTime', models.DateField(null=True)),
                ('ExitTime', models.DateField(null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('propertycode', models.CharField(max_length=30, null=True)),
                ('propertyname', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
