# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-30 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equip_No', models.CharField(help_text='Scan Equipment*', max_length=21, null=True)),
                ('Equip_Name', models.CharField(help_text='Provide  equipment name*', max_length=21, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='attendanceEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(help_text='Provide the names of owner of Equipment*', max_length=100, null=True)),
                ('Tel', models.CharField(help_text='Phone number*', max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facerecognation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_card_No', models.CharField(max_length=21, null=True)),
                ('Names', models.CharField(max_length=50, null=True)),
                ('Tel', models.CharField(max_length=21, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_card_No', models.CharField(help_text='Scan the  ID card*', max_length=21, null=True)),
                ('Names', models.CharField(max_length=50, null=True)),
                ('Destination', models.CharField(choices=[('StaffRoom', 'StaffRoom'), ('ComputerLab', 'ComputerLab'), ('EmployeeRoom', 'EmployeeRoom')], default='StaffRoom', max_length=50, null=True)),
                ('Tel', models.CharField(max_length=21, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idscan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_card_No', models.CharField(help_text='Scan the  ID card*', max_length=21, null=True)),
                ('Names', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipNumber', models.CharField(max_length=30, null=True)),
                ('owner', models.CharField(choices=[('visitor', 'visitor'), ('urrent_instutition', 'current_instutition'), ('visited_instutition', 'visited_instutition')], default='visitor', max_length=30, null=True)),
                ('Id_number', models.CharField(max_length=30, null=True)),
                ('Equip_Name', models.CharField(max_length=30, null=True)),
                ('Tel', models.CharField(max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rfidscan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFId_number', models.CharField(max_length=21, null=True)),
                ('Names', models.CharField(max_length=50, null=True)),
                ('Tel', models.CharField(max_length=21, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(help_text='Provide the names of owner of Equipment*', max_length=100, null=True)),
                ('Tel', models.CharField(help_text='Phone number*', max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ID_card_No', models.ForeignKey(default='', help_text="Visitor's ID Card number*", max_length=21, null=True, on_delete=django.db.models.deletion.CASCADE, to='evisitorsproject.Idscan')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_card_No', models.CharField(help_text='Scan the  ID card*', max_length=21, null=True)),
                ('FirstName', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendanceequip',
            name='ID_card_No',
            field=models.ForeignKey(default='', help_text="Visitor's ID Card number*", max_length=21, null=True, on_delete=django.db.models.deletion.CASCADE, to='evisitorsproject.Idscan'),
        ),
    ]
