# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-30 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfo',
            name='FirstName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
