# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-17 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0002_scanequipment_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanequipment',
            name='Id_number',
        ),
        migrations.AlterField(
            model_name='scanequipment',
            name='EquipName',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('DestopMachine', 'DestopMachine'), ('none', 'none')], default='none', max_length=20, null=True),
        ),
    ]
