# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-06 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0002_auto_20200706_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='idscan',
            name='Department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
