# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-18 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0002_facerecognation_fingerprint_registration_rfidscan_scanequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='idscan',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
