# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-29 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0003_auto_20200717_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='idscan',
            name='Names',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
