# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-06 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0003_idscan_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idscan',
            name='Department',
        ),
        migrations.AddField(
            model_name='idscan',
            name='Destination',
            field=models.CharField(choices=[('StaffRoom', 'StaffRoom'), ('ComputerLab', 'ComputerLab'), ('EmployeeRoom', 'EmployeeRoom')], default='StaffRoom', max_length=50, null=True),
        ),
    ]
