# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-18 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0003_auto_20200518_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idscan',
            name='user',
        ),
    ]
