# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-30 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0004_idscan_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idscan',
            name='Names',
        ),
    ]
