# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-06 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0004_auto_20200706_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facerecognation',
            old_name='First_name',
            new_name='Names',
        ),
        migrations.RenameField(
            model_name='fingerprint',
            old_name='First_name',
            new_name='Names',
        ),
        migrations.RenameField(
            model_name='rfidscan',
            old_name='First_name',
            new_name='Names',
        ),
        migrations.RemoveField(
            model_name='facerecognation',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='facerecognation',
            name='place_Of_Isue',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='place_Of_Isue',
        ),
        migrations.RemoveField(
            model_name='rfidscan',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='rfidscan',
            name='place_Of_Isue',
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='Destination',
            field=models.CharField(choices=[('StaffRoom', 'StaffRoom'), ('ComputerLab', 'ComputerLab'), ('EmployeeRoom', 'EmployeeRoom')], default='StaffRoom', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='idscan',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
