# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0005_auto_20200729_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idscan',
            name='Id_number',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
