# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-18 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0005_remove_idscan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='idscan',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
