# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-29 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0006_auto_20200729_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idscan',
            name='Names',
        ),
    ]
