# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0009_remove_idscan_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanequipment',
            name='Owner',
        ),
        migrations.AlterField(
            model_name='idscan',
            name='Id_number',
            field=models.CharField(help_text='Scan the  ID card*', max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='scanequipment',
            name='Destination',
            field=models.CharField(help_text='Destination is required*', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scanequipment',
            name='EquipName',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('DestopMachine', 'DestopMachine'), ('none', 'none')], default='none', help_text='Type of Equipment*', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scanequipment',
            name='EquipNumber',
            field=models.CharField(help_text="Scan the  equipment's barcode*", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scanequipment',
            name='Names',
            field=models.CharField(help_text='Provide the names of owner of Equipment*', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scanequipment',
            name='Tel',
            field=models.CharField(help_text='Phone number*', max_length=30, null=True),
        ),
    ]
