# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0009_remove_idscan_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='visitorInfo',
        ),
    ]
