# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-03 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0010_delete_visitorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indanga', models.CharField(max_length=30)),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('placeOfIsue', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('propert', models.CharField(max_length=30)),
                ('propertycode', models.CharField(max_length=30)),
                ('propertyname', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Facerecognation',
        ),
        migrations.DeleteModel(
            name='Fingerprint',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Rfidscan',
        ),
        migrations.DeleteModel(
            name='ScanEquipment',
        ),
        migrations.AddField(
            model_name='idscan',
            name='Firstname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='idscan',
            name='Idsican',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='idscan',
            name='Lastname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='idscan',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='idscan',
            name='indanga',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='idscan',
            name='placeOfIsue',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='idscan',
            name='propert',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='idscan',
            name='propertycode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='idscan',
            name='propertyname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
