# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-11 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0011_idscan_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanequipment',
            name='Names',
        ),
        migrations.AlterField(
            model_name='idscan',
            name='Names',
            field=models.CharField(help_text='Names must much*', max_length=50, null=True),
        ),
    ]
