# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-11 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0012_auto_20200811_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanequipment',
            name='Id_number',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='scanequipment',
            name='Owner',
            field=models.CharField(help_text='Names  of the owner*', max_length=30, null=True),
        ),
    ]
