# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-12 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0012_auto_20200611_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idscan',
            old_name='Firstname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='idscan',
            old_name='Lastname',
            new_name='Institution_name',
        ),
        migrations.RenameField(
            model_name='idscan',
            old_name='category',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='idscan',
            old_name='placeOfIsue',
            new_name='place_Of_Isue',
        ),
        migrations.RenameField(
            model_name='idscan',
            old_name='propert',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='idscan',
            old_name='Idsican',
            new_name='property_code',
        ),
        migrations.RemoveField(
            model_name='idscan',
            name='indanga',
        ),
        migrations.RemoveField(
            model_name='idscan',
            name='propertycode',
        ),
        migrations.RemoveField(
            model_name='idscan',
            name='propertyname',
        ),
        migrations.AddField(
            model_name='idscan',
            name='Id_number',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
