# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-11 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0013_auto_20200811_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanequipment',
            old_name='Id_number',
            new_name='Owner_ID',
        ),
    ]
