# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-12 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0014_auto_20200811_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanequipment',
            old_name='Owner_ID',
            new_name='ID_card_No',
        ),
        migrations.RemoveField(
            model_name='idscan',
            name='Names',
        ),
        migrations.RemoveField(
            model_name='scanequipment',
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='scanequipment',
            name='EquipName',
        ),
        migrations.RemoveField(
            model_name='scanequipment',
            name='EquipNumber',
        ),
        migrations.RemoveField(
            model_name='scanequipment',
            name='Owner',
        ),
        migrations.AddField(
            model_name='scanequipment',
            name='Names',
            field=models.CharField(help_text='Provide the names of owner of Equipment*', max_length=100, null=True),
        ),
    ]
