# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0015_auto_20200812_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equip_No', models.CharField(max_length=21, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='attendanceEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_card_No', models.CharField(help_text="Visitor's ID Card number*", max_length=21, null=True)),
                ('Names', models.CharField(help_text='Provide the names of owner of Equipment*', max_length=100, null=True)),
                ('Tel', models.CharField(help_text='Phone number*', max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scanequipment',
            name='ID_card_No',
            field=models.CharField(help_text="Visitor's ID Card number*", max_length=21, null=True),
        ),
    ]
