# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-12 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0015_auto_20200612_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idscan',
            name='property_code',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
