# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-17 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0016_auto_20200814_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idscan',
            old_name='Id_number',
            new_name='ID_card_No',
        ),
    ]
