# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-12 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0017_auto_20200612_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idscan',
            name='First_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
