# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-20 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0017_auto_20200817_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Equip_Name',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
