# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-15 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0019_auto_20200612_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idscan',
            old_name='pub_date',
            new_name='date',
        ),
    ]
