# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-21 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0020_auto_20200615_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_owner', models.CharField(max_length=300, null=True)),
                ('property_code', models.CharField(max_length=300, null=True)),
                ('Institution_name', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='idscan',
            name='Institution_name',
        ),
        migrations.RemoveField(
            model_name='idscan',
            name='property',
        ),
        migrations.RemoveField(
            model_name='idscan',
            name='property_code',
        ),
    ]
