# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-21 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0021_auto_20200621_0450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorProperty',
        ),
        migrations.AddField(
            model_name='idscan',
            name='Institution_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='idscan',
            name='property',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='idscan',
            name='property_code',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
