# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0024_auto_20200621_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facerecognation',
            old_name='FirstName',
            new_name='Last_name',
        ),
        migrations.RemoveField(
            model_name='facerecognation',
            name='EntryTime',
        ),
        migrations.RemoveField(
            model_name='facerecognation',
            name='ExitTime',
        ),
        migrations.RemoveField(
            model_name='facerecognation',
            name='Idnumber',
        ),
        migrations.RemoveField(
            model_name='facerecognation',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='facerecognation',
            name='propertycode',
        ),
        migrations.RemoveField(
            model_name='facerecognation',
            name='propertyname',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='Lastname',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='indanga',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='placeOfIsue',
        ),
        migrations.RemoveField(
            model_name='visitorinfo',
            name='propert',
        ),
        migrations.AddField(
            model_name='facerecognation',
            name='First_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facerecognation',
            name='Id_number',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='facerecognation',
            name='Institution_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='facerecognation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facerecognation',
            name='face',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='facerecognation',
            name='place_Of_Isue',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='facerecognation',
            name='property_code',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='facerecognation',
            name='property_owner',
            field=models.CharField(choices=[('A visitor', ((11, 'v_Laptop'), (12, 'v_tablet'), (13, 'v_Desktop machine'))), ('Instutition', ((11, 'inst_Laptop'), (12, 'inst_tablet'), (13, 'inst_Desktop machine'))), ('current instutition', ((11, 'current_Laptop'), (12, 'current_tablet'), (13, 'current_Desktop machine')))], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='EntryTime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='ExitTime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='FirstName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='Idnumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='LastName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='propertycode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='visitorinfo',
            name='propertyname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
