# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0026_auto_20200621_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerecognation',
            name='face',
            field=models.ImageField(null=True, upload_to='viewReport/'),
        ),
    ]
