# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-21 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0029_auto_20200621_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facerecognation',
            name='face_image',
        ),
    ]
