# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-21 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0030_remove_facerecognation_face_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idscan',
            name='Institution_name',
        ),
        migrations.RemoveField(
            model_name='idscan',
            name='property_code',
        ),
        migrations.RemoveField(
            model_name='idscan',
            name='property_owner',
        ),
        migrations.AddField(
            model_name='facerecognation',
            name='face_image',
            field=models.ImageField(null=True, upload_to='viewReport/'),
        ),
    ]
