# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-21 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0031_auto_20200621_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facerecognation',
            name='Institution_name',
        ),
        migrations.RemoveField(
            model_name='facerecognation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='facerecognation',
            name='property_code',
        ),
        migrations.RemoveField(
            model_name='facerecognation',
            name='property_owner',
        ),
    ]
