# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisitorsproject', '0034_remove_facerecognation_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idscan',
            name='Tel',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
